# Generated by Django 5.2.5 on 2025-10-10 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPosts', '0002_publicaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicaciones',
            name='tag',
        ),
    ]
