# Generated by Django 5.2.5 on 2025-10-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPosts', '0003_remove_publicaciones_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='tags',
            field=models.ManyToManyField(blank=True, to='GestionPosts.tags'),
        ),
    ]
