# Generated by Django 5.2.5 on 2025-10-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPosts', '0005_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(max_length=15),
        ),
    ]
