# Generated by Django 5.2.5 on 2025-10-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPerfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='contraseña2',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
