# Generated by Django 5.2.5 on 2025-10-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPerfil', '0002_usuarios_contraseña2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='rango',
            field=models.IntegerField(default=0),
        ),
    ]
