# Generated by Django 5.2.5 on 2025-10-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPerfil', '0003_alter_usuarios_rango'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='contraseña2',
            field=models.CharField(blank=True, default=models.CharField(max_length=10), max_length=10),
        ),
    ]
