# Generated by Django 5.2.5 on 2025-10-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPerfil', '0007_alter_usuarios_contraseña_alter_usuarios_contraseña2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='contraseña2',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rango',
            field=models.IntegerField(choices=[(0, 'Visitante'), (1, 'Creador'), (2, 'Admin')], default=0),
        ),
    ]
