# Generated by YO!!!!!!!!! soy un humano.
from django.contrib.auth import hashers
from django.db import migrations, models


# https://docs.djangoproject.com/en/5.1/topics/migrations/#data-migrations
def encriptar(apps, schema_editor):
    usuarios = apps.get_model("GestionPerfil", "Usuarios")
    for usuario in usuarios.objects.all():
        usuario.contraseña = hashers.make_password(usuario.contraseña)
        usuario.save()


class Migration(migrations.Migration):
    dependencies = [
        ('GestionPerfil', '0009_alter_usuarios_nombre'),
    ]

    operations = [
        migrations.RunPython(encriptar)
    ]
