# Generated by Django 5.2.5 on 2025-09-27 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('palabra_clave', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('resumen', models.CharField(max_length=500)),
                ('parrafo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuario', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recuento', models.IntegerField(default=0)),
                ('palabra_clave', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Wpedia.informacion')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField(max_length=1000)),
                ('palabra_clave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wpedia.informacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wpedia.usuarios')),
            ],
        ),
    ]
