# Generated by Django 5.2.5 on 2025-09-27 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wpedia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='id',
        ),
        migrations.AlterField(
            model_name='likes',
            name='palabra_clave',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Wpedia.informacion'),
        ),
    ]
