# Generated by Django 5.2.5 on 2025-10-22 00:46

import django.db.models.deletion
import easymde.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionPerfil', '0005_alter_usuarios_contraseña2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=40)),
                ('resumen', models.CharField(max_length=500)),
                ('parrafo', easymde.fields.EasyMDEField(verbose_name='Contenido')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionPerfil.usuarios')),
                ('tags', models.ManyToManyField(blank=True, to='GestionPosts.tags')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionPerfil.usuarios')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionPosts.publicaciones')),
            ],
        ),
    ]
