# Generated by Django 5.2.5 on 2025-10-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tag', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
    ]
