# Generated by Django 5.2.5 on 2025-10-10 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPerfil', '0001_initial'),
        ('GestionPosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=40)),
                ('resumen', models.CharField(max_length=500)),
                ('parrafo', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionPerfil.usuarios')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionPosts.tags')),
            ],
        ),
    ]
