# Generated by Django 5.2.5 on 2025-10-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GestionPosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
