# Generated by Django 5.2.5 on 2025-10-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('GestionPosts', '0002_alter_publicaciones_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tag',
            new_name='contenido',
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag', to='GestionPosts.tags'),
        ),
    ]
