# Generated by Django 5.2.5 on 2025-10-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPosts', '0003_rename_tag_tags_contenido_alter_publicaciones_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag', related_query_name='tag', to='GestionPosts.tags'),
        ),
    ]
