# Generated by Django 5.2.5 on 2025-10-11 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPerfil', '0001_initial'),
        ('GestionPosts', '0004_publicaciones_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionPerfil.usuarios')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionPosts.publicaciones')),
            ],
        ),
    ]
