# Generated by Django 5.2.5 on 2025-10-26 20:20

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPosts', '0004_alter_publicaciones_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='parrafo',
            field=martor.models.MartorField(),
        ),
    ]
