# Generated by Django 5.2.5 on 2025-10-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPosts', '0005_alter_publicaciones_parrafo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
