# Generated by Django 5.2.5 on 2025-11-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPosts', '0006_alter_publicaciones_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='imagen',
            field=models.ImageField(upload_to='imagenes/'),
        ),
    ]
