# Generated by Django 5.2.5 on 2025-10-21 19:12

import easymde.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPosts', '0006_tags_id_alter_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='parrafo',
            field=easymde.fields.EasyMDEField(verbose_name='Contenido'),
        ),
    ]
