# Generated by Django 5.2.5 on 2025-10-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPosts', '0007_alter_publicaciones_parrafo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
