# Generated by Django 5.2.5 on 2025-11-15 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPerfil', '0010_encriptar_contraseñas'),
        ('GestionPosts', '0007_alter_publicaciones_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioBorrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionPerfil.usuarios')),
            ],
        ),
    ]
