# Generated by Django 5.2.5 on 2025-10-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPosts', '0008_alter_tags_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
