# Generated by Django 5.2.5 on 2025-10-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('correo', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('contraseña', models.CharField(max_length=10)),
                ('rango', models.IntegerField()),
            ],
        ),
    ]
