# Generated by Django 5.2.5 on 2025-10-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPerfil', '0004_alter_usuarios_contraseña2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='contraseña2',
            field=models.CharField(default=models.CharField(max_length=10), max_length=10),
        ),
    ]
