# Generated by Django 5.2.5 on 2025-10-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPerfil', '0006_alter_usuarios_contraseña2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='contraseña',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='contraseña2',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
